#!/usr/bin/env python3
"""Generate lib/seal/fe25519.tin: multiplication and squaring mod 2^255 - 19 on ten signed limbs
in radix 2^25.5 (limb i holds bits from ceil(25.5 i)), as straight-line code: no loop, branch or
bounds check, and every product fits in 64 bits for limbs up to 2^27 in magnitude.

Limb offsets add up to one more bit when both limbs are odd (factor 2), and a product past
limb 9 wraps around with factor 19 (2^255 = 19 mod p)."""
import sys


def factor(i, j):
    f = 1
    if i % 2 == 1 and j % 2 == 1:
        f *= 2
    if i + j >= 10:
        f *= 19
    return f


def carry(lines):
    """Bring h0..h9 back to about 2^25 (2^24 for odd limbs), rounding, then store."""
    first = True
    for i in list(range(10)) + [0]:
        w = 26 if i % 2 == 0 else 25
        decl = 'mut c =' if first else 'c ='
        first = False
        lines.append(f'\t{decl} (h{i} + (1 << {w - 1})) >> {w}')
        if i == 9:
            lines.append('\th0 += 19 * c')
        else:
            lines.append(f'\th{i + 1} += c')
        lines.append(f'\th{i} -= c << {w}')
    for i in range(10):
        lines.append(f'\th[{i}] = h{i}')


def scaled(name, k, pre, lines):
    """The name of k*name, defined once."""
    if k == 1:
        return name
    key = f'{name}_{k}'
    if key not in pre:
        pre.add(key)
        lines.append(f'\tlet {key} = {k} * {name}')
    return key


def mul():
    lines = ['// fe_mul sets h = f*g; h may alias f or g. Limbs of f and g up to 2^27 in magnitude.',
             '// The limb bounds keep every sum in i64; @wrap keeps the code free of value-dependent branches.',
             '@wrap fn fe_mul(h mut []i64, f []i64, g []i64) {']
    lines += [f'\tlet f{i} = f[{i}]' for i in range(10)] + [f'\tlet g{i} = g[{i}]' for i in range(10)]
    pre = set()
    body = []
    for k in range(10):
        terms = []
        for i in range(10):
            j = (k - i) % 10
            a = scaled(f'f{i}', 2 if (i % 2 and j % 2) else 1, pre, lines)
            b = scaled(f'g{j}', 19 if i + j >= 10 else 1, pre, lines)
            terms.append(f'{a}*{b}')
        body.append(f'\tmut h{k} = ' + ' + '.join(terms))
    lines += body
    carry(lines)
    lines.append('}')
    return lines


def sq():
    lines = ['// fe_sq sets h = f*f (each cross product once, doubled); h may alias f.',
             '@wrap fn fe_sq(h mut []i64, f []i64) {']
    lines += [f'\tlet f{i} = f[{i}]' for i in range(10)]
    pre = set()
    body = []
    for k in range(10):
        terms = []
        for i in range(10):
            j = (k - i) % 10
            if j < i:
                continue
            m = factor(i, j) * (1 if i == j else 2)
            # Split the constant between the operands to keep both scalings small.
            a_k = 2 if m % 2 == 0 and m != 38 and m != 19 else 1
            if m in (38, 76):
                a_k = m // 19
            b_k = m // a_k
            a = scaled(f'f{i}', a_k, pre, lines)
            b = scaled(f'f{j}', b_k, pre, lines)
            terms.append(f'{a}*{b}')
        body.append(f'\tmut h{k} = ' + ' + '.join(terms))
    lines += body
    carry(lines)
    lines.append('}')
    return lines


def main():
    out = ['// Code generated by tools/gen_fe25519.py; DO NOT EDIT.', '', 'package seal', '']
    out += mul() + [''] + sq()
    sys.stdout.write('\n'.join(out) + '\n')


if __name__ == '__main__':
    main()
